import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs';
const base=process.env.TEST_URL||'http://127.0.0.1:5195/',out=process.env.TEST_OUTPUT||'/tmp/couch-scorecard-evidence';fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE,headless:true});const report=[];
const lum=hex=>{const rgb=hex.match(/\d+/g).slice(0,3).map(Number).map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722;};const contrast=(a,b)=>(Math.max(lum(a),lum(b))+.05)/(Math.min(lum(a),lum(b))+.05);
for(const width of [320,390,1180]){
 const ctx=await browser.newContext({viewport:{width,height:width===1180?757:844},deviceScaleFactor:width===390?2:1,reducedMotion:'reduce'});const p=await ctx.newPage();await p.goto(base+'mnf-2026-10-05/?mode=demo');
 assert(await p.locator('[data-name="0"]').isVisible());const start=await p.locator('[data-action="start"]').boundingBox();assert(start.y+start.height<844,'first start visible');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`${out}/setup-${width}.png`,fullPage:true});
 for(const theme of ['default','seahawks','chargers']){await p.evaluate(theme=>{document.documentElement.dataset.theme=theme},theme);const styles=await p.evaluate(()=>{const e=document.querySelector('[data-action="start"]'),s=getComputedStyle(e),body=getComputedStyle(document.body),note=getComputedStyle(document.querySelector('.setup-intro'));return {primary:[s.color,s.backgroundColor],body:[body.color,body.backgroundColor],muted:[note.color,body.backgroundColor]};});for(const [name,pair]of Object.entries(styles))assert(contrast(...pair)>=4.5,`${theme} ${name} contrast`);report.push({width,theme,contrast:Object.fromEntries(Object.entries(styles).map(([k,v])=>[k,contrast(...v)]))});}
 await p.evaluate(()=>document.documentElement.dataset.theme='default');await p.locator('[data-action="start"]').click();assert.equal(await p.locator('[data-pick]').count(),0);await p.screenshot({path:`${out}/handoff-${width}.png`,fullPage:true});await p.locator('[data-action="open"]').click();await p.locator('[data-pick="0:0"]').click();await p.screenshot({path:`${out}/picks-${width}.png`,fullPage:true});await p.reload();assert.equal(await p.locator('[data-pick]').count(),0);await p.locator('[data-action="predictionboard"]').click();const first=await p.locator('[data-call="0"]').boundingBox();assert(first.y<600,'first prediction visible early');assert.equal(await p.locator('.revealed-player').count(),0);await p.screenshot({path:`${out}/board-${width}.png`,fullPage:true});
 await p.evaluate(()=>{const es=[...document.querySelectorAll('main,main *')];const sizes=es.map(e=>parseFloat(getComputedStyle(e).fontSize)*2);es.forEach((e,i)=>e.style.fontSize=sizes[i]+'px');});await p.screenshot({path:`${out}/overflow-${width}.png`,fullPage:true});const overflow=await p.evaluate(()=>[...document.querySelectorAll('main *')].filter(e=>e.getBoundingClientRect().right>innerWidth).map(e=>({tag:e.tagName,cls:e.className,text:e.textContent.slice(0,90),right:e.getBoundingClientRect().right})));assert.equal(overflow.length,0,JSON.stringify(overflow));await p.screenshot({path:`${out}/board-large-text-${width}.png`,fullPage:true});await ctx.close();
}
fs.writeFileSync(out+'/design-results.json',JSON.stringify({passed:true,report,physicalDevice:false},null,2));await browser.close();console.log('PASS: scorecard 320/390/1180, all-theme text contrast, early action/call, privacy, 200% board text.');
