import vm from 'node:vm';import fs from 'node:fs';import assert from 'node:assert/strict';
const root=new URL('../../',import.meta.url),read=n=>fs.readFileSync(new URL(n,root),'utf8');
const code=['definitions.js','engagement.js','app.js'].map(n=>read('mnf-2026-10-05/'+n)).join('\n'),legacy=read('legacy/legacy.js');
const KEY='couch-clash-web-mnf-2026-10-05-v1',OLD='couch-clash-public-v1',cutoff=Date.parse('2026-10-06T00:15:00Z');
function harness(source=code,stored={},now=cutoff-60000){
 const values=new Map(Object.entries(stored)),writes=[],handlers={},rootEl={innerHTML:'',addEventListener:(t,f)=>handlers[t]=f,querySelector:()=>({focus(){},open:false})};
 const FakeDate=class extends Date{static now(){return now;}};
 const c=vm.createContext({Date:FakeDate,URLSearchParams,crypto:{randomUUID:()=>Math.random().toString(36).slice(2)},console,document:{getElementById:id=>['app','legacy'].includes(id)?rootEl:{textContent:''},documentElement:{dataset:{}},addEventListener(){}},localStorage:{getItem:k=>values.get(k)??null,setItem:(k,v)=>{writes.push(['set',k]);values.set(k,v)},removeItem:k=>{writes.push(['remove',k]);values.delete(k)}},window:{scrollTo(){}},navigator:{},location:{protocol:'file:',search:''},confirm:()=>true,alert(){}});vm.runInContext(source,c);
 return {values,writes,rootEl,c,run:j=>vm.runInContext(j,c),time:n=>now=n,click:d=>handlers.click({target:{closest:()=>({dataset:d,disabled:false,hasAttribute:n=>Object.hasOwn(d,n.replace('data-',''))})}})};
}
const oldGame={version:2,id:'old',mode:'host',phase:'podium',names:['One','Two'],players:[{name:'One',picks:{0:0,1:0,2:0,3:0,4:0},boost:0,locked:[true,true]},{name:'Two',picks:{0:-1,1:-1,2:-1,3:-1,4:-1},boost:null,locked:[true,true]}],round:1,active:1,answers:{0:0,1:0,2:0,3:0,4:0}};
const oldRaw=JSON.stringify({version:2,current:oldGame,history:[{id:'old',savedAt:1,game:oldGame}],theme:'chargers'}),seed={[OLD]:oldRaw,[OLD+':v1-backup']:'unchanged backup'};
function full(mode,voids=false){const h=harness(code,seed);h.run("s.names=['One','Two']");h.click({mode});h.click({action:'start'});for(let r=0;r<2;r++){for(let p=0;p<2;p++){h.click({action:'open'});for(const i of r?[3,4]:[0,1,2])h.click({pick:`${i}:${p?-1:0}`});if(!r&&!p)h.click({boost:'0'});h.click({action:'lock'});}assert.equal(h.run('s.phase'),'watch');h.click({action:'resolve'});h.run(r?`results={2:${voids?-1:0},3:${voids?-1:0},4:${voids?-1:0}}`:`results={0:${voids?-1:0},1:${voids?-1:0}}`);h.click({action:'review'});h.click({action:'confirm'});}return h;}
for(const mode of ['host','demo']){
 const h=full(mode);assert.equal(h.run('score(s.players[0])'),800);assert.equal(h.run('score(s.players[1])'),0);assert(h.rootEl.innerHTML.includes('Winner'));h.click({action:'archive'});h.click({action:'archive'});assert.equal(h.run('history.length'),1);const snapshot=h.run('JSON.stringify(history[0].game.definition)');h.click({action:'reset'});assert.equal(h.run('JSON.stringify(history[0].game.definition)'),snapshot);h.click({history:h.run('history[0].id')});assert(h.rootEl.innerHTML.includes('Falcons'));h.click({action:'historyback'});h.click({action:'eraseall'});for(const [k,v] of Object.entries(seed))assert.equal(h.values.get(k),v);assert(h.writes.every(x=>x[1].startsWith(KEY)));
}
const tie=full('host',true);assert(tie.rootEl.innerHTML.includes('Shared winner'));assert.equal(tie.run('settlement().voided'),5);
for(const offset of [-1,0,1]){const h=harness(code,seed,cutoff+offset);h.click({mode:'host'});h.click({action:'start'});assert.equal(h.run('s.phase'),offset<0?'picks':'setup');}
const late=harness(code,seed);late.click({mode:'host'});late.click({action:'start'});late.click({action:'open'});late.click({pick:'0:0'});late.time(cutoff);late.click({pick:'1:0'});assert.equal(late.run('draft[1]'),undefined);late.click({action:'lock'});assert.equal(late.run('s.players[0].locked[0]'),false);late.click({action:'closecards'});assert.equal(late.run('s.phase'),'watch');assert(late.run('s.players.every(p=>p.locked[0]&&Object.values(p.picks).every(v=>v===-1))'));assert.equal(late.run('Object.keys(s.answers).length'),0);
const no=harness();no.click({mode:'host'});no.click({action:'start'});no.click({action:'closecards'});no.click({action:'resolve'});no.click({action:'review'});assert.equal(no.run('confirming'),false);no.run('results={0:2,1:0}');no.click({action:'review'});assert.equal(no.run('confirming'),false);no.run('results={0:2,1:3}');no.click({action:'review'});assert.equal(no.run('confirming'),true);no.click({action:'confirm'});assert.equal(no.run('s.round'),1);assert(!no.rootEl.innerHTML.includes('revealed-player'));
const old=harness(legacy,seed);old.click({record:'0'});assert(old.rootEl.innerHTML.includes('800 prediction points'));assert(old.rootEl.innerHTML.includes('Seahawks'));assert(!old.rootEl.innerHTML.includes('Pick: Falcons'));assert.equal(old.writes.length,0);
for(const phase of ['picks','watch']){const m=structuredClone(oldGame);m.phase=phase;m.round=0;m.answers={};m.players[0].locked=[phase==='watch',false];const data={version:2,current:m,history:[]};const h=harness(legacy,{[OLD]:JSON.stringify(data),[OLD+':v1-backup']:'backup'});h.click({record:'0'});assert(!h.rootEl.innerHTML.includes('Pick: Seahawks'));h.click({private:'0'});assert(h.rootEl.innerHTML.includes('Pick: Seahawks'));assert(h.rootEl.innerHTML.includes('Pending / concealed'));assert.equal(h.writes.length,0);}
const one=structuredClone(oldGame);one.version=1;const v1=harness(legacy,{[OLD]:JSON.stringify(one)});assert.equal(v1.run('records.length'),1);assert.equal(v1.writes.length,0);
for(const raw of ['{bad',JSON.stringify({version:99})]){const h=harness(code,{[KEY]:raw,...seed});h.click({mode:'host'});assert.equal(h.values.get(KEY),raw);assert.equal(h.writes.length,0);}
const frozen=harness();assert.equal(frozen.run('Object.isFrozen(MNF_DEFINITION.questions[0].opts)'),true);const snap=frozen.run('JSON.stringify(s.definition)');frozen.run("s.definition.questions[0].opts[0]='Wrong'");assert.notEqual(frozen.run('JSON.stringify(MNF_DEFINITION)'),frozen.run('JSON.stringify(s.definition)'));assert.equal(frozen.run('validDefinition(s.definition)'),false);assert(snap.includes('Falcons'));

// Closing halftime preserves already-locked cards; missing results never become voids.
no.click({action:'open'});no.click({pick:'3:0'});no.click({pick:'4:0'});no.click({action:'lock'});const lockedCard=no.run('JSON.stringify(s.players[0])');no.click({action:'closecards'});assert.equal(no.run('JSON.stringify(s.players[0])'),lockedCard);assert.equal(no.run('s.players[1].picks[3]'),-1);assert.equal(no.run('s.answers[2]'),undefined);
const incomplete=structuredClone(oldGame);delete incomplete.answers[4];const incompleteView=harness(legacy,{[OLD]:JSON.stringify({version:2,current:incomplete,history:[]})});incompleteView.click({record:'0'});assert(!incompleteView.rootEl.innerHTML.includes(' · Winner'));assert(incompleteView.rootEl.innerHTML.includes('Not final'));
// A later unsupported definition must be refused, not reinterpret an existing match.
const saved=full('demo');saved.click({action:'archive'});const stored=saved.values.get(KEY);const changedCode=code.replaceAll('Atlanta Falcons','Different Team');const refused=harness(changedCode,{[KEY]:stored,...seed});assert.equal(refused.run('invalidStore'),true);assert.equal(refused.values.get(KEY),stored);assert.equal(refused.writes.length,0);


for(const raw of ['{bad',JSON.stringify({version:88})]){const h=harness(legacy,{[OLD]:raw});assert(h.rootEl.innerHTML.includes('not')||h.rootEl.innerHTML.includes('Nothing'));assert.equal(h.writes.length,0);assert.equal(h.values.get(OLD),raw);}
const corrupt=full('demo');const corruptStore=JSON.parse(corrupt.values.get(KEY));corruptStore.current.players[0].picks[0]=99;const corruptRaw=JSON.stringify(corruptStore);const invalid=harness(code,{[KEY]:corruptRaw});assert.equal(invalid.run('invalidStore'),true);assert.equal(invalid.values.get(KEY),corruptRaw);


const actualDemo=harness();actualDemo.run("s.names=['One','Two']");actualDemo.click({action:'start'});for(let round=0;round<2;round++){for(let player=0;player<2;player++){actualDemo.click({action:'open'});for(const i of round?[3,4]:[0,1,2])actualDemo.click({pick:`${i}:${player?-1:0}`});if(!round&&!player)actualDemo.click({boost:'0'});actualDemo.click({action:'lock'});}actualDemo.click({action:'resolve'});actualDemo.click({action:'review'});actualDemo.click({action:'confirm'});}assert.equal(actualDemo.run('score(s.players[0])'),200);assert.equal(actualDemo.run('score(s.players[1])'),0);

console.log('PASS: max800/manual/demo/ties/voids/skip/pending/no-score/cutoff/host-close/legacy-v1-v2-readonly/frozen-definition/unknown-data/history/erase');
