'use strict';
const KEY='couch-clash-local-scores-test-v1';
const matchQuestions=()=>s.definition.questions;
const uid=()=>globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
const fresh=()=>({version:3,definition:JSON.parse(JSON.stringify(MNF_DEFINITION)),id:uid(),mode:'demo',phase:'setup',names:['Player 1','Player 2','Player 3'],players:[],round:0,answers:{},active:0});
const themes={default:'Default',seahawks:'Seahawks colors',chargers:'Chargers colors'};
let s=fresh(),history=[],theme='default',libraryOpen=false,historyId=null,savedAt=null,boardOpen=false;
let storageOK=true,invalidStore=false,legacyBackup=null,notice='',screen='',draft={},boost=null,results={},confirming=false;
const clone=x=>JSON.parse(JSON.stringify(x));
function validChoices(x){return !!x&&typeof x==='object'&&!Array.isArray(x)&&Object.entries(x).every(([k,v])=>/^[0-4]$/.test(k)&&Number.isInteger(v)&&v>=-1&&v<MNF_DEFINITION.questions[+k].opts.length);}
function validMatch(m){return !!m&&typeof m.id==='string'&&m.version===3&&validDefinition(m.definition)&&['demo','host'].includes(m.mode)&&['setup','picks','watch','resolve','podium'].includes(m.phase)&&Array.isArray(m.names)&&m.names.length>=2&&m.names.length<=6&&m.names.every(n=>typeof n==='string')&&Array.isArray(m.players)&&m.players.length<=6&&(m.phase==='setup'||m.players.length>=2)&&m.players.every(p=>typeof p.name==='string'&&validChoices(p.picks)&&(p.boost===null||[0,1,2].includes(p.boost))&&Array.isArray(p.locked)&&p.locked.length===2&&p.locked.every(x=>typeof x==='boolean'))&&[0,1].includes(m.round)&&Number.isInteger(m.active)&&m.active>=0&&(m.phase==='setup'||m.active<m.players.length)&&validChoices(m.answers);}
try{
 const raw=localStorage.getItem(KEY),old=raw?JSON.parse(raw):null;
 if(old?.version===3&&validMatch(old.current)&&Array.isArray(old.history)&&old.history.length<=20&&old.history.every(r=>r&&typeof r.id==='string'&&Number.isFinite(r.savedAt)&&validMatch(r.game)&&r.game.phase==='podium')){
  s=old.current;history=old.history;theme=Object.hasOwn(themes,old.theme)?old.theme:'default';libraryOpen=old.paused===true;savedAt=old.savedAt;boardOpen=old.boardOpen===true;
 }else if(old!==null){invalidStore=true;storageOK=false;}
 else if(new URLSearchParams(location.search).get('mode')==='host')s.mode='host';
}catch(e){storageOK=false;invalidStore=true;}
// Entry links may choose a mode only on setup; never replace an active match.
const requestedMode=new URLSearchParams(location.search).get('mode');
if(!invalidStore&&s.phase==='setup'&&['host','demo'].includes(requestedMode))s.mode=requestedMode;
const app=document.getElementById('app');
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ids=()=>s.round===0?[0,1,2]:[3,4];
const outcomeIds=()=>s.round===0?[0,1]:[2,3,4];
function save(){
 if(invalidStore)return false;
 try{
  if(legacyBackup!==null){if(localStorage.getItem(KEY+':v1-backup')===null)localStorage.setItem(KEY+':v1-backup',legacyBackup);legacyBackup=null;}
  const time=Date.now();localStorage.setItem(KEY,JSON.stringify({version:3,current:s,history,theme,paused:libraryOpen,boardOpen,savedAt:time}));savedAt=time;storageOK=true;return true;
 }catch(e){storageOK=false;return false;}
}
function say(t){document.getElementById('announce').textContent=t;}
function move(){save();render();window.scrollTo(0,0);const h=app.querySelector('h1');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}}
function couchMark(){return `<svg class="couch-mark" viewBox="0 0 160 104" fill="none" aria-hidden="true"><path d="M30 53V29Q30 15 44 15H116Q130 15 130 29V53M23 85V95M137 85V95" stroke="currentColor" stroke-width="5" stroke-linecap="round"/><path d="M30 60H130M80 22V58" stroke="currentColor" stroke-width="2" stroke-dasharray="4 5"/><path d="M20 48Q8 48 8 61V75Q8 86 20 86H140Q152 86 152 75V61Q152 48 140 48Q130 48 130 60V67H30V60Q30 48 20 48Z" fill="var(--panel)" stroke="currentColor" stroke-width="5"/><path d="M23 77H137" stroke="currentColor" stroke-width="2" stroke-dasharray="4 5"/></svg>`;}
function header(){return `<header><div class="brand">couch<em>clash</em>${couchMark()}</div><span class="tag ${s.mode==='demo'?'demo':''}">${s.phase==='setup'?'ONE PHONE · YOUR CREW':s.mode==='demo'?'SIMULATED DEMO':'MANUAL HOST'}</span></header><p class="preview-label">ATL at NO · October 5, 2026</p>`;}
function steps(){return `<nav class="steps" aria-label="Match progress">${['Pregame','Halftime','Podium'].map((x,i)=>`<div class="step ${i===(s.phase==='podium'?2:s.round)?'active':''}">${String(i+1).padStart(2,'0')} / ${x}</div>`).join('')}</nav>`;}
function kickoffPassed(){return Date.now()>=Date.parse(s.definition.fixture.kickoff);}
function fixture(){return `<section class="fixture-strip" aria-label="Selected game"><strong>ATL <span>at</span> NO</strong><div>Falcons at Saints<small>Oct 5 · 5:15 PM Pacific · ${kickoffPassed()?'Status unverified':'Scheduled'}</small></div></section>`;}
function cutoffMessage(){return 'Scheduled kickoff has passed on this device. New pregame picks are closed. Try the fictional demo; already locked calls stay saved.';}
function canPick(){return s.mode==='demo'||s.round===1||!kickoffPassed();}
function closeCardsControl(){return !libraryOpen&&s.mode==='host'&&s.phase==='picks'?'<button class="secondary" data-action="closecards">Host: play started · close remaining cards</button><p class="note">Unsubmitted cards become skips worth 0. Locked cards and confirmed outcomes stay unchanged. Use this when kickoff or the third quarter begins.</p>':'';}
function cutoffNotice(){return s.mode==='host'?`<p class="note cutoff-note">${kickoffPassed()?cutoffMessage():'Pregame starts and locks close at scheduled kickoff using this device’s clock. The host must stop picks if play starts earlier.'} Halftime cards close when the host says play is restarting. This is a local courtesy rule, not a live feed or server anti-cheat.</p>`:'';}
function rules(){return `<details><summary>How scoring & privacy work</summary><p>Couch Clash prediction points are separate from the football score. Pregame: 100 per correct call. Boost one call to 200; wrong calls never lose points. Halftime: 200 per correct call. Maximum: 800.</p><p>Misses, skips and voided calls earn 0. Equal scores share a rank and the win. No speed bonus. Locks cannot be undone without resetting the match.</p><p>One device, passed around. Handoff screens hide cards until results; anyone with this device can inspect its local data. No account, analytics, network feed or phone-to-phone sync. The current match and any saved history stay in this browser/app installation. Reset current match keeps MNF history; Erase MNF data only removes this fixture’s current match and history. October 4 web saves are preserved. Clearing browser/app data can erase everything. Local saves are not accounts or cross-device sync.</p></details>`;}
function setup(){return `${fixture()}<h1 class="setup-title">Who’s on the couch?</h1><p class="setup-intro">One phone. 2–6 people. Five calls to settle.</p><div class="names">${s.names.map((n,i)=>`<label class="name"><span class="avatar a${i%3}" aria-hidden="true">${i+1}</span><span class="sr">Player ${i+1} name</span><input data-name="${i}" value="${esc(n)}" maxlength="18" autocomplete="off"></label>`).join('')}</div><div class="crew-tools"><button class="textbtn" data-action="add" ${s.names.length>=6?'disabled':''}>+ Add player</button><button class="textbtn" data-action="remove" ${s.names.length<=2?'disabled':''}>Remove last</button></div><div class="modegrid"><button data-mode="host" class="${s.mode==='host'?'selected':''}" aria-pressed="${s.mode==='host'}">Host this game<small>You enter the outcomes</small></button><button data-mode="demo" class="${s.mode==='demo'?'selected':''}" aria-pressed="${s.mode==='demo'}">Try a quick demo<small>Made-up results · play now</small></button></div><button class="primary" data-action="start" ${s.mode==='host'&&kickoffPassed()?'disabled':''}>${s.mode==='demo'?'Start the demo':'Start our match'}</button><p class="note">Three calls now. Two at halftime. Pass the phone after each card.</p>${cutoffNotice()}${rules()}<p class="note">No live feed. <a href="https://www.neworleanssaints.com/schedule/" target="_blank" rel="noopener">Schedule source</a></p>${recentRecap()}<details><summary>Add to your Home Screen</summary><p>In Safari, tap Share, then Add to Home Screen. Progress stays in this browser; separate phones do not share a match. Offline use needs a completed first load.</p></details><p class="note"><a href="../legacy/">October 4 web saves · read-only</a> · <a href="../">Game picker</a></p>`;}
// Explanatory copy only: positional question/option/scoring definitions stay unchanged.
function footballHelp(i){
 const basics=[
  'The first half is the first two quarters. Pick the first team to score before halftime. “No score” means neither team scored in that half.',
  'A touchdown scores 6 football points, a field goal 3, and a safety 2. Extra points and two-point tries follow a touchdown; this call excludes those tries.',
  'Overtime is extra play after regulation ends tied. Use the final result after any overtime. Choose Tie only if the game ends tied.',
  'Compare how many football points each team adds after halftime, including any overtime—not the final scoreboard totals.',
  'Add the football points both teams score after halftime, including any overtime. The bands use that combined total—not the final game total.'
 ];
 const example=i>=3?'<p><strong>Made-up example:</strong> Halftime: Falcons 14–7 Saints. Final: Falcons 21–17 Saints. After halftime: Falcons 21 − 14 = 7; Saints 17 − 7 = 10. Saints lead that period; the combined 7 + 10 = 17 belongs in 0–20. These are not real game results.</p>':'';
 return `<details class="football-help"><summary>Football help & example</summary><p>${basics[i]}</p>${example}<p>Football points belong to the game on TV. Couch Clash prediction points reward correct calls; they do not change the football score.</p><p><a href="https://operations.nfl.com/rules-officiating/nfl-football-basics/football-terms" target="_blank" rel="noopener noreferrer">Official NFL football glossary ↗</a> · opens online</p></details>`;
}
function pickScreen(){let p=s.players[s.active];if(screen!=='card')return `${steps()}<section class="handoff"><div class="eyebrow">${s.round?'HALFTIME COMEBACK':'PREGAME CALLS'} · ${s.active+1} OF ${s.players.length}</div><div class="handoff-seat">${couchMark()}</div><h1><span>Pass to</span> ${esc(p.name)}</h1><p class="intro" style="margin:auto">${s.round?'Two calls. 400 points up for grabs. Plenty of room for a comeback.':'Three quick calls. Boost your boldest one. Then eyes on the game.'}</p><button class="primary" data-action="open">That’s me · open my card</button><p class="note">Your picks stay hidden until the reveal.</p></section>${s.round===1?`<div class="card"><div class="eyebrow">FIRST-HALF REVEAL</div><p>${s.answers[0]>=0?matchQuestions()[0].opts[s.answers[0]]:"Void"} · ${s.answers[1]>=0?matchQuestions()[1].opts[s.answers[1]]:"Void"}</p><p class="note">Winner call stays locked until the final whistle.</p></div>`:""}${board(s.round===1)}<button class="secondary" data-action="predictionboard">View prediction board</button>`;
return `${steps()}<div class="eyebrow">${esc(p.name)}’S ${s.round?'HALFTIME':'PREGAME'} CARD</div><h1>${s.round?'Still anyone’s game.':'Call your shot.'}</h1><p class="note">${s.round?'200 prediction points each. Lock before the third quarter begins.':'Lock before kickoff. 100 prediction points each. Optional: boost one call to double its prediction points.'}</p>${cutoffNotice()}${ids().map(i=>`<fieldset class="question"><legend><span class="slip-number">${String(i+1).padStart(2,'0')}</span> ${matchQuestions()[i].title}</legend><p class="note question-scope">${esc(matchQuestions()[i].when)}</p><div class="qmeta"><span class="note">${matchQuestions()[i].points} points${boost===i?' × 2':''}</span>${s.round?'':`<button class="boost ${boost===i?'selected':''}" data-boost="${i}" aria-pressed="${boost===i}">${boost===i?'Boosted ×2':'Boost ×2'}</button>`}</div><div class="options">${matchQuestions()[i].opts.map((o,j)=>`<button data-pick="${i}:${j}" aria-pressed="${draft[i]===j}" class="${draft[i]===j?'selected':''}">${o}</button>`).join('')}</div><button class="skip ${draft[i]===-1?'selected':''}" data-pick="${i}:-1" aria-pressed="${draft[i]===-1}">${draft[i]===-1?'Skipped · 0 points':'Skip this call · 0 points'}</button>${footballHelp(i)}</fieldset>`).join('')}<button class="primary" data-action="lock" ${!canPick()||ids().some(i=>draft[i]===undefined)?'disabled':''}>Lock ${s.round?'2':'3'} calls & pass →</button><p class="note">Choose an answer or explicitly skip each call. Locked picks cannot be changed.</p>`;}
function points(p,i,answers=s.answers){return answers[i]>=0&&p.picks[i]===answers[i]?matchQuestions()[i].points*(p.boost===i?2:1):0;}
function score(p,answers=s.answers){return matchQuestions().reduce((n,q,i)=>n+points(p,i,answers),0);}
function ranked(){return s.players.map((p,i)=>({...p,id:i,total:score(p)})).sort((a,b)=>b.total-a.total);}
function board(reveal=true){return `<section class="card"><h3>${reveal?'The couch standings':'Crew check'}</h3>${ranked().map((p,i,all)=>`<div class="scoreline"><span class="rank">${reveal?all.findIndex(x=>x.total===p.total)+1:'•'}</span><span class="avatar a${p.id%3}">${esc(p.name[0].toUpperCase())}</span><div class="who"><strong>${esc(p.name)}</strong><div class="status">${reveal?(s.phase==='podium'?(p.total===all[0].total?(all.filter(x=>x.total===p.total).length>1?'Shared winner':'Winner'):'Finished'):(p.total===all[0].total?'In the lead':'Still in it')):p.locked[s.round]?'Card locked':'Getting ready'}</div></div>${reveal?`<span class="pts">${p.total}</span>`:''}</div>`).join('')}</section>`;}
function watch(){return predictionBoard();}
function resolver(){return `${steps()}${settlementStrip()}<div class="eyebrow">${s.mode==='demo'?'FICTIONAL DEMO OUTCOMES':'HOST OUTCOME DESK'}</div><h1>${confirming?'Check the reveal.':s.round?'The final calls.':'Halftime reveal.'}</h1><p class="muted">${confirming?'Check these outcomes before scoring. Once confirmed, they are locked.':s.mode==='demo'?'A made-up match for this rehearsal. No real score or live data.':'Record what happened on your broadcast. If an event is cancelled or unclear, void that call.'}</p>${outcomeIds().map(i=>`<div class="card"><label for="out${i}"><strong>${matchQuestions()[i].title}</strong><p class="note">${matchQuestions()[i].when}</p></label>${confirming?`<strong>${results[i]===-1?'Void · 0 for everyone':matchQuestions()[i].opts[results[i]]}</strong>`:`<select id="out${i}" data-outcome="${i}" ${s.mode==='demo'?'disabled':''}><option value="">Choose outcome…</option>${matchQuestions()[i].opts.map((x,j)=>`<option value="${j}" ${results[i]===j?'selected':''}>${x}</option>`).join('')}<option value="-1" ${results[i]===-1?'selected':''}>Void · 0 for everyone</option></select>`}</div>`).join('')}${confirming?'<button class="primary" data-action="confirm">Confirm outcomes & reveal →</button><button class="secondary" data-action="backresults">Back to outcomes</button>':`<button class="primary" data-action="review" ${outcomeIds().some(i=>results[i]===undefined)?'disabled':''}>Review outcomes →</button><button class="textbtn" data-action="backwatch">Not time yet · back to game</button>`}`;}
function breakdown(){return `<details><summary>Every call, every point</summary>${s.players.map(p=>`<h3>${esc(p.name)} · ${score(p)} pts</h3>${matchQuestions().map((q,i)=>`<div class="result"><span>${q.title}<br><small>${p.picks[i]>=0?q.opts[p.picks[i]]:'Skipped'}${p.boost===i?' · boosted':''}</small></span><span>+${points(p,i)}<br><small>Result: ${s.answers[i]>=0?q.opts[s.answers[i]]:'Void'}</small></span></div>`).join('')}`).join('')}</details>`;}
function podium(readOnly=false){return groupRecap(readOnly);}
function localTools(){return `<details class="local-tools"><summary>Theme & local saves</summary><h2 class="settings-title">Make it yours.</h2><fieldset class="theme-choices"><legend>Theme for this device</legend>${Object.entries(themes).map(([id,label])=>`<button data-theme="${id}" class="${theme===id?'selected':''}" aria-pressed="${theme===id}">${theme===id?'✓ ':''}${label}</button>`).join('')}</fieldset><p class="note">Pass-and-play shares one theme. Anyone holding this phone can change it. These are not separate player accounts.</p><button class="secondary" data-action="library" ${s.phase==='resolve'?'disabled':''}>${s.phase!=='setup'?'Save & leave':'Saved games on this device'}</button>${s.phase==='resolve'?'<p class="note">Confirm the outcomes or go back to the game before saving and leaving.</p>':''}<p class="note">Progress saves automatically here. No cloud backup or phone-to-phone sync. Clearing browser/app data can erase saves.</p></details>`;}
function gameLabel(m){return `Falcons at Saints · Oct 5 · ${m.mode==='demo'?'Demo':'Manual host'} · ${m.phase==='podium'?'Completed':m.round?'Halftime':'Pregame'}`;}
function savedGames(){return `<div class="eyebrow">ON THIS DEVICE ONLY</div><h1>Your local games.</h1><p class="note">Shared by everyone using this browser or app installation. No accounts or cross-device restore. Saving does not pause the broadcast.</p>${s.phase!=='setup'?`<section class="card"><h2>Current match</h2><p>${gameLabel(s)}</p><p class="note">${s.players.map(p=>esc(p.name)).join(' · ')}</p><button class="primary" data-action="resume">Resume saved match →</button><p class="note">${storageOK?'Saved on this device.':'Not saved reliably. Keep this window open.'} Locks stay in place.</p></section>`:''}<button class="secondary" data-action="${s.phase==='setup'?'resume':'reset'}">${s.phase==='setup'?'Back to setup':'Start a new match'}</button><div class="divider"></div><h2>Saved recaps <span class="note">${history.length} / 20</span></h2><p class="note">Use Save final game on the recap to keep it here. Replay and current-match reset keep this history.</p>${history.length?history.map(r=>`<section class="card saved-card"><h3>${esc(r.game.players.map(p=>p.name).join(' · '))}</h3><p class="note">${gameLabel(r.game)} · saved ${esc(new Date(r.savedAt).toLocaleString())}</p><button class="secondary" data-history="${esc(r.id)}">Open saved recap</button><button class="textbtn" data-delete="${esc(r.id)}">Delete this saved game</button></section>`).join(''):'<p class="note">No completed games saved yet.</p>'}<div class="divider"></div><button class="textbtn danger" data-action="eraseall">Erase MNF data only</button><p class="note">Deletes this MNF match, its completed history and theme only. October 4 web saves are kept.</p>`;}
function render(){
 document.documentElement.dataset.theme=theme;
 const warning=invalidStore?'Stored data could not be read safely. It has not been overwritten. Use Saved games → Erase MNF data only only if you want to delete it.':!storageOK?'Browser storage unavailable. Changes are not safely saved. Keep this window open; reload may lose progress.':'';
 const banner=(warning?`<div class="alert">${warning}</div>`:'')+(notice?`<p class="save-notice" role="status">${esc(notice)}</p>`:'');
 const record=history.find(r=>r.id===historyId);
 if(record){const current=s;s=record.game;app.innerHTML=header()+banner+'<button class="secondary" data-action="historyback">← Back to local games</button>'+podium(true);s=current;return;}
 app.innerHTML=header()+banner+(libraryOpen?savedGames():boardOpen&&s.phase==='picks'?predictionBoard():(s.phase==='setup'?setup():s.phase==='picks'?pickScreen():s.phase==='watch'?watch():s.phase==='resolve'?resolver():podium()))+closeCardsControl()+localTools()+(!libraryOpen&&s.phase!=='setup'?'<div class="divider"></div><button class="textbtn" data-action="reset">Reset current match</button>':'');
}
function focusHeading(){window.scrollTo(0,0);const h=app.querySelector('h1');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}}
function resumeMatch(){boardOpen=false;libraryOpen=false;historyId=null;notice='';screen='';if(s.phase==='resolve')s.phase='watch';save();render();focusHeading();}
function resetCurrent(){
 const unsaved=s.phase==='podium'&&!history.some(r=>r.id===s.id);
 if(!confirm(`${unsaved?'This completed game is not saved to history. ':''}Delete the current match and start fresh? Saved completed history and theme will be kept.`))return;
 const previous=s;boardOpen=false;s=fresh();libraryOpen=false;historyId=null;screen='';draft={};results={};confirming=false;notice='';
 if(!save()){s=previous;notice='Reset could not be saved. The current match was kept.';}
 render();focusHeading();
}
app.addEventListener('input',e=>{if(e.target.dataset.name!==undefined){s.names[+e.target.dataset.name]=e.target.value;save();}});
app.addEventListener('change',e=>{if(e.target.dataset.outcome!==undefined){let i=+e.target.dataset.outcome;if(e.target.value==='')delete results[i];else results[i]=+e.target.value;const b=app.querySelector('[data-action="review"]');b.disabled=outcomeIds().some(i=>results[i]===undefined);}});
app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const d=b.dataset;
if(d.theme){const old=theme;theme=d.theme;if(!save()){theme=old;notice='Theme was not saved. Your previous theme was kept.';}else notice='Theme saved for this device.';render();const details=app.querySelector('.local-tools');if(details)details.open=true;app.querySelector(`[data-theme="${theme}"]`)?.focus();return;}
if(d.history){historyId=d.history;libraryOpen=true;notice='';save();render();focusHeading();return;}
if(d.delete){if(confirm('Delete this completed game from local history? Your current match and other saved games will be kept.')){const old=history;history=history.filter(r=>r.id!==d.delete);if(!save()){history=old;notice='Deletion could not be saved. The game was kept.';}else notice='Saved game deleted.';render();focusHeading();}return;}
notice='';
if(d.mode){s.mode=d.mode;save();render();return;}
if(d.pick){if(!canPick()){notice=cutoffMessage();render();return;}const [i,j]=d.pick.split(':').map(Number);draft[i]=j;saveDraft();render();app.querySelector(`[data-pick="${d.pick}"]`).focus();say(j<0?'Call skipped':matchQuestions()[i].opts[j]+' selected');return;}
if(d.boost!==undefined){if(!canPick()){notice=cutoffMessage();render();return;}boost=boost===+d.boost?null:+d.boost;saveDraft();render();app.querySelector(`[data-boost="${d.boost}"]`).focus();return;}
switch(d.action){case 'closecards':if(s.mode!=='host'||s.phase!=='picks')return;if(!confirm('Close every unsubmitted card for this round as skips worth 0? Locked cards stay unchanged. Use this only when play has started.'))return;for(const p of s.players){if(!p.locked[s.round]){for(const i of ids())p.picks[i]=-1;if(s.round===0)p.boost=null;p.locked[s.round]=true;}}s.active=s.players.length-1;s.phase='watch';screen='';boardOpen=false;draft={};boost=null;notice='Unsubmitted cards closed as skips. Outcomes are still pending.';move();break;case 'predictionboard':boardOpen=true;screen='';save();render();focusHeading();break;case 'backtocards':boardOpen=false;screen='';save();render();focusHeading();break;case 'add':s.names.push('Player '+(s.names.length+1));move();break;case 'remove':s.names.pop();move();break;
case 'start':{if(s.mode==='host'&&kickoffPassed()){notice=cutoffMessage();render();return;}const names=s.names.map((n,i)=>n.trim()||'Player '+(i+1));if(new Set(names.map(n=>n.toLowerCase())).size<names.length){say('Use different names so the scoreboard stays clear.');alert('Give each player a different name.');return;}s.names=names;s.players=names.map(name=>({name,picks:{},boost:null,locked:[false,false]}));s.phase='picks';s.active=0;screen='';move();break;}
case 'open':screen='card';draft={...s.players[s.active].picks};boost=s.players[s.active].boost;move();break;
case 'lock':if(!canPick()){notice=cutoffMessage();render();return;}if(ids().some(i=>draft[i]===undefined)||s.players[s.active].locked[s.round])return;s.players[s.active].picks={...draft};s.players[s.active].boost=boost;s.players[s.active].locked[s.round]=true;screen='';if(s.active<s.players.length-1)s.active++;else s.phase='watch';move();say('Card locked.');break;
case 'resolve':boardOpen=false;s.phase='resolve';results=s.mode==='demo'?(s.round?{2:1,3:1,4:1}:{0:0,1:1}):{};confirming=false;move();break;
case 'backwatch':s.phase='watch';move();break;case 'review':if(outcomeIds().some(i=>results[i]===undefined))return;if(s.round===0&&results[0]!==-1&&results[1]!==-1&&((results[0]===2)!==(results[1]===3))){alert('No score must match on both first-half calls. Check the outcomes or void an unclear call.');return;}confirming=true;move();break;case 'backresults':confirming=false;move();break;
case 'confirm':if(outcomeIds().some(i=>results[i]===undefined))return;Object.assign(s.answers,results);s.outcomeConfirmedAt={...(s.outcomeConfirmedAt||{}),[s.round]:Date.now()};if(s.round===0){s.round=1;s.active=0;s.phase='picks';screen='';}else s.phase='podium';move();say(s.phase==='podium'?'Final scores revealed':'First calls scored. Halftime round unlocked.');break;
case 'reset':resetCurrent();break;
case 'library':boardOpen=false;if(s.phase==='resolve')return;libraryOpen=true;historyId=null;screen='';if(save())notice='Saved on this device.';else notice='Save failed. Keep this window open.';render();focusHeading();break;
case 'resume':resumeMatch();break;
case 'historyback':historyId=null;render();focusHeading();break;
case 'archive':if(s.phase!=='podium'||history.some(r=>r.id===s.id))return;if(history.length>=20){notice='History is full. Delete a saved game before saving another. Nothing was removed.';render();return;}history=[{id:s.id,savedAt:Date.now(),game:clone(s)},...history];if(!save()){history=history.filter(r=>r.id!==s.id);notice='Final game was not saved. Keep this match open and try again.';}else notice='Final game saved to local history.';render();say(notice);break;
case 'eraseall':if(confirm('Permanently erase this October 5 MNF game, its history and theme? October 4 web saves and native-app saves are not affected. This cannot be undone.')){try{localStorage.removeItem(KEY+':v1-backup');localStorage.removeItem(KEY);s=fresh();history=[];theme='default';libraryOpen=false;historyId=null;savedAt=null;boardOpen=false;screen='';draft={};results={};legacyBackup=null;invalidStore=false;storageOK=true;notice='MNF data erased. October 4 web saves were not touched.';}catch(e){storageOK=false;notice='Erasing data failed. Some local data may remain.';}render();focusHeading();}break;
}});
function saveDraft(){if(s.phase==='picks'&&!s.players[s.active].locked[s.round]){s.players[s.active].picks={...draft};s.players[s.active].boost=boost;save();}}
// On reload, private card always returns behind the handoff screen. Outcome desk restarts safely.
if(s.phase==='resolve')s.phase='watch';
if(legacyBackup!==null)save();
window.render_game_to_text=()=>JSON.stringify({mode:s.mode,phase:s.phase,round:s.round,view:screen||'handoff',active:s.players[s.active]?.name,players:s.players.map(p=>({name:p.name,locked:p.locked,score:score(p)})),answers:s.answers,storageOK,theme,localView:historyId?'history':libraryOpen?'saved-games':'match',historyCount:history.length});
window.advanceTime=()=>{};
render();

// Recheck scheduled cutoff when returning to the app; mutations also check it.
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&s.mode==='host')render();});
