import http from 'node:http';import {readFile} from 'node:fs/promises';import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH);
const root=new URL('../CouchClash/ForecastWeb/',import.meta.url).pathname;
const server=http.createServer(async(req,res)=>{const file={'/':'index.html','/pilot.js':'pilot.js','/style.css':'style.css'}[req.url];if(!file){res.writeHead(404);return res.end()}res.setHeader('Content-Type',file.endsWith('.html')?'text/html':file.endsWith('.js')?'text/javascript':'text/css');res.end(await readFile(root+file))});await new Promise(r=>server.listen(64803,'127.0.0.1',r));
const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE});
try{
 for(const scenario of ['normal','unavailable','refused','timeout','malformed','cancel','journal-change','identical-recreate']){
  const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();
  await page.addInitScript(scenario=>{window.packets=[];window.webkit={messageHandlers:{forecastSelection:{postMessage:body=>{window.packets.push(body);if(body.operation==='cancel')return Promise.resolve({version:1,requestID:body.requestID,status:'cancel_ack'});if(['cancel','journal-change','identical-recreate'].includes(scenario))return new Promise(r=>window.late=()=>r({version:1,requestID:body.requestID,status:'ok',selection:'oneEventNotSkill'}));return Promise.resolve({version:1,requestID:body.requestID,status:scenario==='normal'||scenario==='malformed'?'ok':scenario,...(['normal','malformed'].includes(scenario)?{selection:scenario==='normal'?'oneEventNotSkill':'invented-cause'}:{})})}}}}},scenario);
  await page.goto('http://127.0.0.1:64803');const button=page.getByRole('button',{name:'Ask on-device model'});assert.equal(await button.isDisabled(),true);
  await page.getByLabel('Your probability').fill('50');await page.getByLabel('Your reason').fill('PRIVATE_SENTINEL');await page.getByRole('button',{name:'Save before'}).click();assert.equal(await button.isDisabled(),false);await button.click();
  if(scenario==='cancel'){await page.getByRole('button',{name:'Cancel highlight'}).click();await page.evaluate(()=>window.late());await page.waitForTimeout(30);assert.match(await page.locator('#native-status').textContent(),/^Cancelled/)}
  else if(['journal-change','identical-recreate'].includes(scenario)){const before=await page.evaluate(()=>localStorage.getItem('couch-clash-ios-forecast-journal-v1'));await page.getByLabel('Delete only').check();await page.getByRole('button',{name:'Delete journal',exact:true}).click();if(scenario==='identical-recreate'){await page.getByRole('button',{name:'Save before'}).click();assert.equal(await page.evaluate(()=>localStorage.getItem('couch-clash-ios-forecast-journal-v1')),before);}await page.evaluate(()=>window.late());await page.waitForTimeout(30);assert.ok(!(await page.locator('#native-status').textContent()).startsWith('On-device selection'))}
  else {await page.waitForFunction(()=>!document.getElementById('native-select').disabled);assert.match(await page.locator('#native-status').textContent(),scenario==='normal'?/^On-device selection/:/^Deterministic fallback/)}
  const packets=await page.evaluate(()=>window.packets);assert.ok(packets.length);assert.ok(packets.every(p=>Object.keys(p).sort().join('|')==='evidenceIDs|operation|packet|requestID|version'&&p.packet==='synthetic-one-event-v1'&&JSON.stringify(p.evidenceIDs)==='["E1"]'));assert.ok(!JSON.stringify(packets).includes('PRIVATE_SENTINEL'));console.log('PASS JS FAKE:',scenario);await context.close();
 }
}finally{await browser.close();await new Promise(r=>server.close(r));}
