import http from 'node:http';import {readFile,writeFile} from 'node:fs/promises';import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH),root=new URL('../CouchClash/ForecastWeb/',import.meta.url);
const server=http.createServer(async(req,res)=>{const f={'/':'index.html','/pilot.js':'pilot.js','/style.css':'style.css'}[req.url];if(!f){res.writeHead(404);return res.end()}res.setHeader('Content-Type',f.endsWith('html')?'text/html':f.endsWith('js')?'text/javascript':'text/css');res.end(await readFile(new URL(f,root)))});await new Promise(r=>server.listen(64804,'127.0.0.1',r));
const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE}),errors=[];
try{for(const width of [320,390,768]){
 const context=await browser.newContext({viewport:{width,height:844},deviceScaleFactor:2,reducedMotion:'reduce'}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{window.exportStatus='saved';window.exported=null;window.webkit={messageHandlers:{forecastSelection:{postMessage:b=>Promise.resolve({version:1,requestID:b.requestID,status:'unavailable'})},forecastJournalExport:{postMessage:b=>{window.exported=b;if(window.exportStatus==='pending')return new Promise(r=>window.finishExport=()=>r({version:1,requestID:b.requestID,status:'saved'}));return Promise.resolve({version:1,requestID:b.requestID,status:window.exportStatus})}}}}});
 await page.goto('http://127.0.0.1:64804');await page.getByLabel('Your probability').fill('80');await page.getByLabel('Your reason').fill('Original synthetic reason');await page.getByRole('button',{name:'Save before'}).click();
 await page.getByText('Synthetic test driver',{exact:true}).click();await page.getByRole('button',{name:'Advance clock'}).click();await page.getByLabel('Your probability').fill('60');await page.getByRole('button',{name:'Save before'}).click();await page.getByRole('button',{name:'Next day'}).click();await page.reload();assert.ok(await page.getByRole('button',{name:'Save before'}).isDisabled());
 await page.getByText('Synthetic test driver',{exact:true}).click();await page.getByLabel('Append synthetic outcome').selectOption('no');await page.getByRole('button',{name:'Append outcome record'}).click();await page.getByText('Original Brier: 0.6400',{exact:true}).waitFor();await page.getByText('Final pre-cutoff Brier: 0.3600',{exact:true}).waitFor();
 await context.setOffline(true);await page.getByRole('button',{name:'Explain this review'}).click();await page.getByText('Deterministic review',{exact:true}).waitFor();
 for(const status of ['saved','cancelled','failed']){await page.evaluate(s=>window.exportStatus=s,status);await page.getByRole('button',{name:'Export journal JSON'}).click();assert.match(await page.locator('#message').textContent(),status==='saved'?/^Exported journal/:status==='cancelled'?/^Export cancelled/:/^Export failed/)}
 await page.evaluate(()=>window.exportStatus='pending');await page.getByRole('button',{name:'Export journal JSON'}).click();assert.ok(await page.getByRole('button',{name:'Export journal JSON'}).isDisabled());assert.match(await page.locator('#message').textContent(),/^Choose a destination in Files/);await page.evaluate(()=>window.finishExport());await page.waitForFunction(()=>!document.getElementById('export').disabled);assert.match(await page.locator('#message').textContent(),/^Exported journal/);
 const data=await page.evaluate(()=>window.exported);assert.equal(data.operation,'saveJournalJSON');assert.equal(JSON.parse(data.json).forecasts.length,2);assert.equal(Object.keys(data).sort().join('|'),'json|operation|requestID|version');
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>document.documentElement.style.fontSize='28px');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>document.documentElement.style.fontSize='');
 await page.screenshot({path:new URL(`evidence/layout-${width}.png`,import.meta.url).pathname,fullPage:true});await page.getByLabel('Delete only').check();await page.getByRole('button',{name:'Delete journal',exact:true}).click();assert.equal(await page.evaluate(()=>localStorage.getItem('couch-clash-ios-forecast-journal-v1')),null);assert.ok(await page.getByRole('button',{name:'Ask on-device model'}).isDisabled());
 await context.close();console.log('PASS iOS bundle layout/export/delete',width);
}assert.deepEqual(errors,[]);}finally{await browser.close();await new Promise(r=>server.close(r))}
